#!/usr/bin/env bash
#
# Guard against orphaned test suites: every test/*.sh suite must actually be
# run somewhere, or be explicitly accounted for. A suite that exists but no
# job invokes is dead weight that rots silently (we found rebase, large-merge,
# persist-failure, and remote suites in exactly this state).
#
# The same applies to doltlite-native testfixture suites (test/doltlite_*.test):
# each must be listed in a regression bucket (test/regression-buckets/*.txt) so a
# CI job runs it. (Inherited upstream *.test files are gated selectively via the
# buckets + divergence tracking, so they are NOT required here.) The .test class
# was originally unchecked, so doltlite_gc_stop_world.test and
# doltlite_reload_uncommitted_recent.test shipped without a bucket line and ran
# nowhere until this guard was extended to cover them.
#
# A suite counts as "run" if its basename is referenced by:
#   - any .github/workflows/*.yml (explicit invocation), or
#   - a CI glob those workflows expand (oracle_*_test.sh, vc_oracle_*_test.sh), or
#   - a regression bucket (test/regression-buckets/*.txt), for *.test suites, or
#   - test/lib/doltlite_suite_manifest.sh, test/run_c_tests.sh, or
#   - main.mk (lint targets run via `make`),
# or it is listed in one of the two manifests beside this script:
#   - test/ci_suite_allowlist.txt   suites run by a dedicated mechanism that
#                                   the greps above don't catch, with a reason.
#   - test/ci_suite_quarantine.txt  suites known NOT to run (broken/stale),
#                                   each with a reason — visible, tracked debt.
#
# C tests (test/*_test.c) are checked the same way: each must be named by
# test/run_c_tests.sh, a workflow, or the manifest, or be listed. That class was
# unchecked, and concurrent_commit_test.c had been running nowhere long enough to
# rot -- three dolt_log counts had gone stale against the seed commit.
#
# Differential-fuzzer groups are checked too: a group in the generator's GROUPS
# list that no job selects is generated by nothing. Ten groups were in exactly
# that state -- the sweep took the pull-request default set everywhere, so the
# nightly never ran them either.
#
# Non-suite scripts (harnesses, libs, perf drivers) are skipped via EXCLUDE.
#
# Exit nonzero (listing the offenders) if any suite is neither run nor listed.

set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Scripts that are not test suites: runners/harnesses, the shared lib, perf
# drivers, and this guard itself.
is_excluded() {
  case "$1" in
    run_*.sh|lib/*|sysbench*.sh|time-*.sh|*wordcount*.sh|lint_orphaned_suites.sh)
      return 0 ;;
    *) return 1 ;;
  esac
}

allowlist="$SCRIPT_DIR/ci_suite_allowlist.txt"
quarantine="$SCRIPT_DIR/ci_suite_quarantine.txt"

listed_in() {  # listed_in <file> <basename>
  [ -f "$1" ] || return 1
  grep -vE '^\s*(#|$)' "$1" | grep -Fxq "$2"
}

# A *.test suite is gated if its basename (no extension) is listed in a
# regression bucket, which a CI job runs via `testfixture`.
in_bucket() {  # in_bucket <basename-without-.test>
  cat test/regression-buckets/*.txt 2>/dev/null \
    | grep -vE '^\s*(#|$)' | grep -Fxq "$1"
}

# A reference is "real" if it appears outside this guard and the manifests.
referenced() {
  local base="$1"
  grep -rIlF "$base" \
      .github/workflows/ \
      test/lib/doltlite_suite_manifest.sh test/run_c_tests.sh main.mk \
      2>/dev/null | grep -q .
}

# CI globs the workflows expand at runtime.
matches_ci_glob() {
  case "$1" in
    oracle_*_test.sh|vc_oracle_*_test.sh)
      grep -rqE "oracle_\*_test\.sh|vc_oracle_\*_test\.sh" .github/workflows/ ;;
    *) return 1 ;;
  esac
}

orphans=()
quarantined=0
for path in test/*.sh; do
  base="$(basename "$path")"
  is_excluded "$base" && continue
  if referenced "$base" || matches_ci_glob "$base" || listed_in "$allowlist" "$base"; then
    continue
  fi
  if listed_in "$quarantine" "$base"; then
    quarantined=$((quarantined + 1))
    continue
  fi
  orphans+=("$base")
done

# doltlite-native testfixture suites: each must be gated in a regression bucket
# (or explicitly allowlisted). Inherited upstream *.test files are excluded --
# they are gated selectively, not one-per-file.
for path in test/doltlite_*.test; do
  [ -e "$path" ] || continue
  base="$(basename "$path")"
  name="${base%.test}"
  if in_bucket "$name" || referenced "$base" || listed_in "$allowlist" "$base"; then
    continue
  fi
  if listed_in "$quarantine" "$base"; then
    quarantined=$((quarantined + 1))
    continue
  fi
  orphans+=("$base")
done

# C tests. A mention in main.mk only means the binary can be built, so this
# asks the narrower question: does something actually run it? That is
# test/run_c_tests.sh's gating arrays, a workflow step, or the suite manifest.
c_test_gated() {  # c_test_gated <name-without-.c>
  grep -rIlF "$1" \
      test/run_c_tests.sh .github/workflows/ \
      test/lib/doltlite_suite_manifest.sh \
      2>/dev/null | grep -q .
}

for path in test/*_test.c; do
  [ -e "$path" ] || continue
  base="$(basename "$path")"
  if c_test_gated "${base%.c}" || listed_in "$allowlist" "$base"; then
    continue
  fi
  if listed_in "$quarantine" "$base"; then
    quarantined=$((quarantined + 1))
    continue
  fi
  orphans+=("$base")
done

# Differential-fuzzer groups: every group the generator can emit has to be
# selected by some job, or it is dead coverage. A job counts if it names the
# group or asks for every group.
group_orphans=()
if [ -f test/sql_differential_fuzzer.py ]; then
  # Only real selections count. The divergence-report step echoes a reproduce
  # command containing this variable, and a printed hint runs nothing.
  selections() {
    grep -rhE "DOLTLITE_DIFF_GROUPS=" .github/workflows/ 2>/dev/null \
      | grep -vE "^[[:space:]]*(#|echo|printf)"
  }
  if selections | grep -qE "DOLTLITE_DIFF_GROUPS=[\"']?all\b"; then
    : # a job sweeps every group
  else
    while IFS= read -r g; do
      [ -z "$g" ] && continue
      selections | grep -qF "$g" || group_orphans+=("$g")
    done < <(sed -n '/^GROUPS = \[/,/\]/p' test/sql_differential_fuzzer.py \
             | grep -oE '"[a-z-]+"' | tr -d '"')
  fi
fi

# Manifest hygiene: an allow/quarantine entry that no longer exists, or a
# quarantined suite that is now also wired in, is stale — flag it so the
# lists don't drift.
stale=()
for f in "$allowlist" "$quarantine"; do
  [ -f "$f" ] || continue
  while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    [ -f "test/$entry" ] || stale+=("$entry (listed in $(basename "$f"), no such suite)")
  done < <(grep -vE '^\s*(#|$)' "$f")
done
while IFS= read -r entry; do
  [ -z "$entry" ] && continue
  if referenced "$entry" || matches_ci_glob "$entry"; then
    stale+=("$entry (quarantined but now run — remove from quarantine)")
  fi
done < <(grep -vE '^\s*(#|$)' "$quarantine" 2>/dev/null || true)

rc=0
if [ "${#orphans[@]}" -ne 0 ]; then
  echo "ERROR: orphaned test suites (run nowhere; wire into a runner/workflow,"
  echo "       or add to test/ci_suite_allowlist.txt / ci_suite_quarantine.txt):"
  printf '  - %s\n' "${orphans[@]}"
  rc=1
fi
if [ "${#group_orphans[@]}" -ne 0 ]; then
  echo "ERROR: differential-fuzzer groups no job selects (dead coverage):"
  printf '  - %s\n' "${group_orphans[@]}"
  echo "       Point a job at them (DOLTLITE_DIFF_GROUPS), or drop the group."
  rc=1
fi
if [ "${#stale[@]}" -ne 0 ]; then
  echo "ERROR: stale manifest entries:"
  printf '  - %s\n' "${stale[@]}"
  rc=1
fi

if [ "$rc" -eq 0 ]; then
  echo "OK: every test suite is run or accounted for (${quarantined} quarantined)."
fi
exit $rc
