#!/usr/bin/tclsh
#
# To build a single huge source file holding all of SQLite (or at
# least the core components - the test harness, shell, and TCL
# interface are omitted.) first do
#
#      make target_source
#
# The make target above moves all of the source code files into
# a subdirectory named "tsrc".  (This script expects to find the files
# there and will not work if they are not found.)  There are a few
# generated C code files that are also added to the tsrc directory.
# For example, the "parse.c" and "parse.h" files to implement the
# the parser are derived from "parse.y" using lemon.  And the
# "keywordhash.h" files is generated by a program named "mkkeywordhash".
#
# After the "tsrc" directory has been created and populated, run
# this script:
#
#      tclsh mksqlite3c.tcl [flags] [extra source files]
#
# The amalgamated SQLite code will be written into sqlite3.c
#

set help {Usage: tclsh mksqlite3c.tcl <options>
 where <options> is zero or more of the following with these effects:
   --nostatic     => Do not generate with compile-time modifiable linkage.
   --linemacros=?  => Emit #line directives into output or not. (? = 1 or 0)
   --useapicall   => Prepend functions with SQLITE_APICALL or SQLITE_CDECL.
   --srcdir $SRC  => Specify the directory containing constituent sources.
   --help         => See this.
 The value setting options default to --linemacros=1 and '--srcdir tsrc' .
}

# Begin by reading the "sqlite3.h" header file.  Extract the version number
# from in this file.  The version number is needed to generate the header
# comment of the amalgamation.
#

set addstatic 1
set linemacros 0
set useapicall 0
set enable_recover 0
set doltlite 0
set skipstructs 0
set skipfns [list]
set srcdir tsrc
set extrasrc [list]

for {set i 0} {$i<[llength $argv]} {incr i} {
  set x [lindex $argv $i]
  if {[regexp {^-?-enable-recover$} $x]} {
    set enable_recover 1
  } elseif {[regexp {^-?-doltlite$} $x]} {
    set doltlite 1
  } elseif {[regexp {^-?-nostatic$} $x]} {
    set addstatic 0
  } elseif {[regexp {^-?-linemacros(?:=([01]))?$} $x ma ulm]} {
    if {$ulm == ""} {set ulm 1}
    set linemacros $ulm
  } elseif {[regexp {^-?-useapicall$} $x]} {
    set useapicall 1
  } elseif {[regexp {^-?-srcdir$} $x]} {
    incr i
    if {$i==[llength $argv]} {
      error "No argument following $x"
    }
    set srcdir [lindex $argv $i]
  } elseif {[regexp {^-?-((help)|\?)$} $x]} {
    puts $help
    exit 0
  } elseif {[regexp {^-?-} $x]} {
    error "unknown command-line option: $x"
  } else {
    lappend extrasrc $x
  }
}
set in [open $srcdir/sqlite3.h rb]
set cnt 0
set VERSION ?????
while {![eof $in]} {
  set line [gets $in]
  if {$line=="" && [eof $in]} break
  incr cnt
  regexp {#define\s+SQLITE_VERSION\s+"(.*)"} $line all VERSION
}
close $in

# Open the output file and write a header comment at the beginning
# of the file.
#
set fname sqlite3.c
if {$enable_recover} { set fname sqlite3r.c }
set tmpfname "$fname.tmp-[pid]-[clock clicks]"
set out [open $tmpfname {WRONLY CREAT EXCL}]
# Force the output to use unix line endings, even on Windows.
fconfigure $out -translation binary
try {
set today [clock format [clock seconds] -format "%Y-%m-%d %H:%M:%S UTC" -gmt 1]
puts $out [subst \
{/******************************************************************************
** This file is an amalgamation of many separate C source files from SQLite
** version $VERSION.  By combining all the individual C code files into this
** single large file, the entire code can be compiled as a single translation
** unit.  This allows many compilers to do optimizations that would not be
** possible if the files were compiled separately.  Performance improvements
** of 5% or more are commonly seen when SQLite is compiled as a single
** translation unit.
**
** This file is all you need to compile SQLite.  To use SQLite in other
** programs, you need this file and the "sqlite3.h" header file that defines
** the programming interface to the SQLite library.  (If you do not have
** the "sqlite3.h" header file at hand, you will find a copy embedded within
** the text of this file.  Search for "Begin file sqlite3.h" to find the start
** of the embedded sqlite3.h header file.) Additional code files may be needed
** if you want a wrapper to interface SQLite with your choice of programming
** language. The code for the "sqlite3" command-line shell is also in a
** separate file. This file contains only code for the core SQLite library.
**}]
set srcroot [file dirname [file dirname [info script]]]
if {$tcl_platform(platform) eq "windows"} {
  set vsrcprog src-verify.exe
} else {
  set vsrcprog ./src-verify
}
if {[file executable $vsrcprog] && [file readable $srcroot/manifest]} {
  set tmpfile tmp-[clock millisec]-[expr {int(rand()*100000000000)}].txt
  exec $vsrcprog -x $srcroot > $tmpfile
  set fd [open $tmpfile rb]
  set res [string trim [split [read $fd] \n]]
  close $fd
  file delete -force $tmpfile
  puts $out "** The content in this amalgamation comes from Fossil check-in"
  puts -nonewline $out "** [string range [lindex $res 0] 0 35]"
  if {[llength $res]==1} {
    puts $out "."
  } else {
    puts $out " with changes in files:\n**"
    foreach f [lrange $res 1 end] {
       puts $out "**    [string trim $f]"
    }
  }
} else {
  puts $out "** The origin of the sources used to build this amalgamation"
  puts $out "** is unknown."
}
puts $out [subst {*/
#ifndef SQLITE_AMALGAMATION
#define SQLITE_CORE 1
#define SQLITE_AMALGAMATION 1}]
if {$addstatic} {
  puts $out \
{#ifndef SQLITE_PRIVATE
# define SQLITE_PRIVATE static
#endif}
}
if {$doltlite} {
  # This amalgamation has the prolly storage engine and version-control layer
  # woven in; the btree orig/shim split it relies on only makes sense with
  # DOLTLITE_PROLLY defined. Bake it in so the single file is self-contained and
  # consumers that compile sqlite3.c without -DDOLTLITE_PROLLY still build it as
  # doltlite rather than a half-wired stock SQLite.
  puts $out \
{#ifndef DOLTLITE_PROLLY
# define DOLTLITE_PROLLY 1
#endif
#ifndef DOLTLITE_VERSION
# define DOLTLITE_VERSION "doltlite-amalgamation"
#endif
#ifndef DOLTLITE_ENABLE_REMOTES
# define DOLTLITE_ENABLE_REMOTES 1
#endif
#if DOLTLITE_ENABLE_REMOTES
# define DOLTLITE_AMALGAMATION_AUTH 1
# define DOLTLITE_AUTH_CLIENT_ONLY 1
# define DOLTLITE_HAVE_AUTH 1
#endif

/* winsock2.h must precede SQLite's first windows.h include. */
#ifdef _WIN32
# include <winsock2.h>
# include <ws2tcpip.h>
#endif}
  set seen_hdr(winsock2.h) 1
  set seen_hdr(ws2tcpip.h) 1
}

# Examine the parse.c file.  If it contains lines of the form:
#
#    "#ifndef SQLITE_ENABLE_UPDATE_LIMIT
# 
# then set the SQLITE_UDL_CAPABLE_PARSER flag in the amalgamation.
#
set in [open $srcdir/parse.c rb]
if {[regexp {ifndef SQLITE_ENABLE_UPDATE_DELETE_LIMIT} [read $in]]} {
  puts $out "#define SQLITE_UDL_CAPABLE_PARSER 1"
}
close $in

# These are the header files used by SQLite.  The first time any of these
# files are seen in a #include statement in the C code, include the complete
# text of the file in-line.  The file only needs to be included once.
#
foreach hdr {
   btree.h
   btreeInt.h
   fts3.h
   fts3Int.h
   fts3_hash.h
   fts3_tokenizer.h
   geopoly.c
   hash.h
   hwtime.h
   keywordhash.h
   msvc.h
   mutex.h
   opcodes.h
   os_common.h
   os_setup.h
   os_win.h
   os.h
   pager.h
   parse.h
   pcache.h
   pragma.h
   rtree.h
   sqlite3session.h
   sqlite3.h
   sqlite3ext.h
   sqlite3rbu.h
   sqliteicu.h
   sqliteInt.h
   sqliteLimit.h
   vdbe.h
   vdbeInt.h
   vxworks.h
   wal.h
   whereInt.h
   sqlite3recover.h
} {
  set available_hdr($hdr) 1
}
set available_hdr(sqliteInt.h) 0
set available_hdr(os_common.h) 0
set available_hdr(sqlite3session.h) 0

# doltlite: register the prolly/chunk/doltlite local headers so copy_file
# inlines (and dedups) them instead of emitting raw #include lines.
if {$doltlite} {
  foreach hdr {
    blake3.h blake3_impl.h btree_orig_api.h btree_orig_prefix.h pager_shim.h record_codec.h sortkey.h
    chunk_file.h chunk_index.h chunk_refs.h chunk_staging.h chunk_store.h chunk_store_int.h chunk_wal.h
    prolly_cache.h prolly_check.h prolly_chunk_walk.h prolly_chunker.h prolly_cursor.h
    prolly_diff.h prolly_encoding.h prolly_hash.h prolly_hashset.h prolly_mutate.h
    prolly_mutmap.h prolly_node.h prolly_record.h prolly_three_way_diff.h
    prolly_three_way_merge.h prolly_xxhash.h prolly_btree_int.h
    doltlite_ancestor.h doltlite_catalog_types.h doltlite_chunk_walk.h doltlite_commit.h
    doltlite_constraint_violations.h doltlite_ignore.h doltlite_internal.h
    doltlite_branch_int.h doltlite_merge_int.h doltlite_merge_constraints_int.h
    doltlite_name_index.h doltlite_parse.h
    doltlite_record.h doltlite_remote.h doltlite_vtab_util.h
    doltlite_creds.h doltlite_mbedtls_config.h doltlite_net.h doltlite_tls.h
  } {
    set available_hdr($hdr) 1
  }
  foreach path [glob -nocomplain $srcdir/ed25519/*.h] {
    set tail [file tail $path]
    set hdr ed25519/$tail
    set available_hdr($hdr) 1
    set available_hdr_path($hdr) $path
    if {$tail ne "sha512.h"} {
      set available_hdr($tail) 1
      set available_hdr_path($tail) $path
    }
  }
  foreach dir {mbedtls psa} {
    foreach path [glob -nocomplain $srcdir/$dir/*.h] {
      set hdr "$dir/[file tail $path]"
      set available_hdr($hdr) 1
      set available_hdr_path($hdr) $path
    }
  }
  foreach path [glob -nocomplain $srcdir/mbedtls_library/*.h] {
    set hdr [file tail $path]
    set available_hdr($hdr) 1
    set available_hdr_path($hdr) $path
  }
}

# These headers should be copied into the amalgamation without modifying any
# of their function declarations or definitions.
set varonly_hdr(sqlite3.h) 1

# These are the functions that accept a variable number of arguments.  They
# always need to use the "cdecl" calling convention even when another calling
# convention (e.g. "stcall") is being used for the rest of the library.
set cdecllist {
  sqlite3_config
  sqlite3_db_config
  sqlite3_log
  sqlite3_mprintf
  sqlite3_snprintf
  sqlite3_test_control
  sqlite3_vtab_config
}

# 78 stars used for comment formatting.
set s78 \
{*****************************************************************************}

# Insert a comment into the code
#
proc section_comment {text} {
  global out s78
  set n [string length $text]
  set nstar [expr {60 - $n}]
  if {$nstar<0} {set nstar 0}
  set stars [string range $s78 0 $nstar]
  puts $out "/************** $text $stars/"
}

# Read the source file named $filename and write it into the
# sqlite3.c output file.  If any #include statements are seen,
# process them appropriately.
#
proc copy_file {filename} {
  global seen_hdr available_hdr available_hdr_path varonly_hdr cdecllist out
  global addstatic linemacros useapicall srcdir skipstructs skipfns
  set ln 0
  set tail [file tail $filename]
  section_comment "Begin file $tail"
  if {$linemacros} {puts $out "#line 1 \"$filename\""}
  set in [open $filename rb]
  set varpattern {^[a-zA-Z][a-zA-Z_0-9 *]+(sqlite3[_a-zA-Z0-9]+)(\[|;| =)}
  set declpattern {([a-zA-Z][a-zA-Z_0-9 ]+ \**)(sqlite3[_a-zA-Z0-9]+)(\(.*)}
  if {[file extension $filename]==".h"} {
    set declpattern " *$declpattern"
  }
  set declpattern ^$declpattern\$
  while {![eof $in]} {
    set line [string trimright [gets $in]]
    incr ln
    # doltlite: when re-inlining a header for the orig-prefixed storage block,
    # skip top-level aggregate definitions (struct/union/enum {...};) — they are
    # already defined by the earlier unprefixed inline and would redefine here.
    # Function prototypes/typedefs/macros are kept (prototypes get orig_-renamed).
    if {$skipstructs && [regexp {^(struct|union|enum)[ \t][^;]*\{} $line]} {
      set depth [expr {[regexp -all {\{} $line] - [regexp -all {\}} $line]}]
      while {$depth>0 && ![eof $in]} {
        set sl [string trimright [gets $in]]
        incr depth [expr {[regexp -all {\{} $sl] - [regexp -all {\}} $sl]}]
      }
      continue
    }
    # doltlite: skip declarations of the named functions (e.g. doltlite-added
    # btree API not part of the orig engine) when re-inlining a header; consume
    # any multi-line prototype through its terminating ';'.
    if {[llength $skipfns]} {
      set hit 0
      foreach fn $skipfns {
        if {[string first $fn $line]>=0} {set hit 1; break}
      }
      if {$hit} {
        while {![string match {*;*} $line] && ![eof $in]} {
          set line [string trimright [gets $in]]
        }
        continue
      }
    }
    if {[regexp {^\s*#\s*include\s+["<]([^">]+)[">]} $line all hdr]} {
      if {[string first / $hdr]<0
          && [string match */ed25519/* $filename]
          && [info exists available_hdr(ed25519/$hdr)]} {
        set hdr ed25519/$hdr
      } elseif {[string first / $hdr]<0
          && [string match */psa/* $filename]
          && [info exists available_hdr(psa/$hdr)]} {
        set hdr psa/$hdr
      } elseif {[string first / $hdr]<0
          && [info exists available_hdr(mbedtls/$hdr)]} {
        set hdr mbedtls/$hdr
      }
      # A doltlite source may include a registered header by a relative path
      # (e.g. "../ext/blake3/blake3.h"); normalize to the basename so it inlines.
      if {![info exists available_hdr($hdr)]
          && [info exists available_hdr([file tail $hdr])]} {
        set hdr [file tail $hdr]
      }
      if {[info exists available_hdr($hdr)]} {
        if {$available_hdr($hdr)} {
          set available_hdr($hdr) 0
          section_comment "Include $hdr in the middle of $tail"
          if {[info exists available_hdr_path($hdr)]} {
            set mapped_path $available_hdr_path($hdr)
            foreach alias [array names available_hdr_path] {
              if {$available_hdr_path($alias) eq $mapped_path} {
                set available_hdr($alias) 0
              }
            }
            copy_file $mapped_path
          } else {
            copy_file $srcdir/$hdr
          }
          if {$hdr eq "mbedtls/mbedtls_config.h"
              && $available_hdr(doltlite_mbedtls_config.h)} {
            set available_hdr(doltlite_mbedtls_config.h) 0
            copy_file $srcdir/doltlite_mbedtls_config.h
          }
          section_comment "Continuing where we left off in $tail"
          if {$linemacros} {puts $out "#line [expr {$ln+1}] \"$filename\""}
        } else {
          # Comment out the entire line, replacing any nested comment
          # begin/end markers with the harmless substring "**".
          puts $out "/* [string map [list /* ** */ **] $line] */"
        }
      } elseif {![info exists seen_hdr($hdr)]} {
        if {![regexp {/\*\s+amalgamator:\s+dontcache\s+\*/} $line]} {
          set seen_hdr($hdr) 1
        }
        puts $out $line
      } elseif {[regexp {/\*\s+amalgamator:\s+keep\s+\*/} $line]} {
        # This include file must be kept because there was a "keep"
        # directive inside of a line comment.
        puts $out $line
      } else {
        # Comment out the entire line, replacing any nested comment
        # begin/end markers with the harmless substring "**".
        puts $out "/* [string map [list /* ** */ **] $line] */"
      }
    } elseif {[regexp {^#ifdef __cplusplus} $line]} {
      puts $out "#if 0"
    } elseif {!$linemacros && [regexp {^#line} $line]} {
      # Skip #line directives.
    } elseif {$addstatic
               && ![regexp {^(static|typedef|SQLITE_PRIVATE)} $line]} {
      # Skip adding the SQLITE_PRIVATE or SQLITE_API keyword before
      # functions if this header file does not need it.
      if {![info exists varonly_hdr($tail)]
       && [regexp $declpattern $line all rettype funcname rest]} {
        regsub {^SQLITE_API } $line {} line
        regsub {^SQLITE_API } $rettype {} rettype

        # Add the SQLITE_PRIVATE or SQLITE_API keyword before functions.
        # so that linkage can be modified at compile-time.
        if {[regexp {^sqlite3[a-z]*_} $funcname]} {
          set line SQLITE_API
          append line " " [string trim $rettype]
          if {[string index $rettype end] ne "*"} {
            append line " "
          }
          if {$useapicall} {
            if {[lsearch -exact $cdecllist $funcname] >= 0} {
              append line SQLITE_CDECL " "
            } else {
              append line SQLITE_APICALL " "
            }
          }
          append line $funcname $rest
          if {$funcname=="sqlite3_sourceid"} {
            # The sqlite3_sourceid() routine is synthesized at the end of
            # the amalgamation
            puts $out "/* $line */"
          } else {
            puts $out $line
          }
        } else {
          puts $out "SQLITE_PRIVATE $line"
        }
      } elseif {[regexp $varpattern $line all varname]} {
          # Add the SQLITE_PRIVATE before variable declarations or
          # definitions for internal use
          regsub {^SQLITE_API } $line {} line
          if {![regexp {^sqlite3_} $varname]
              && ![regexp {^sqlite3Show[A-Z]} $varname]} {
            regsub {^extern } $line {} line
            puts $out "SQLITE_PRIVATE $line"
          } else {
            if {[regexp {const char sqlite3_version\[\];} $line]} {
              set line {const char sqlite3_version[] = SQLITE_VERSION;}
            }
            regsub {^SQLITE_EXTERN } $line {} line
            puts $out "SQLITE_API $line"
          }
      } elseif {[regexp {^(SQLITE_EXTERN )?void \(\*sqlite3IoTrace\)} $line]} {
        regsub {^SQLITE_API } $line {} line
        regsub {^SQLITE_EXTERN } $line {} line
        puts $out $line
      } elseif {[regexp {^void \(\*sqlite3Os} $line]} {
        regsub {^SQLITE_API } $line {} line
        puts $out "SQLITE_PRIVATE $line"
      } else {
        puts $out $line
      }
    } else {
      puts $out $line
    }
  }
  close $in
  section_comment "End of $tail"
}

proc reset_auth_headers {headers} {
  global available_hdr
  foreach hdr $headers {
    set available_hdr($hdr) 1
  }
}

proc copy_file_isolated {filename {renames {}}} {
  global out
  set names {}
  set in [open $filename rb]
  while {![eof $in]} {
    set line [gets $in]
    if {[regexp {^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)} $line all name]
        && [lsearch -exact $names $name]<0} {
      lappend names $name
    }
  }
  close $in
  foreach {name replacement} $renames {
    if {[lsearch -exact $names $name]<0} {lappend names $name}
  }
  foreach name $names {
    puts $out "#pragma push_macro(\"$name\")"
  }
  foreach {name replacement} $renames {
    puts $out "#define $name $replacement"
  }
  copy_file $filename
  foreach name [lreverse $names] {
    puts $out "#pragma pop_macro(\"$name\")"
  }
}

# Read the source file named $filename and write it into the
# sqlite3.c output file. The only transformation is the trimming
# of EOL whitespace.
#
proc copy_file_verbatim {filename} {
  global out
  set in [open $filename rb]
  set tail [file tail $filename]
  section_comment "Begin EXTRA_SRC file $tail"
  while {![eof $in]} {
    set line [string trimright [gets $in]]
    puts $out $line
  }
  section_comment "End of EXTRA_SRC $tail"
}

# doltlite: emit the stock storage engine (pager/wal/btmutex/btree/backup) with
# its external symbols renamed to orig_* so it can coexist in one translation
# unit with prolly_btree.c/pager_shim.c (which export the unprefixed
# sqlite3Btree*/sqlite3Pager* entry points). Mirrors the separate-compilation
# btree_orig.o/pager_orig.o/... objects (main.mk), where btree_orig_prefix.h is
# force-included. The orig bodies need prefixed prototypes, so pager.h/wal.h/
# btree.h are re-inlined here with the rename active (struct/enum defs skipped —
# they were already emitted unprefixed earlier via sqliteInt.h).
proc emit_doltlite_storage_block {} {
  global out srcdir available_hdr skipstructs skipfns
  section_comment "doltlite: BEGIN orig_* storage engine block"
  # Names that are conditional functions or no-op macros in btree.h/pager.h.
  # Emit the btree renames under the same conditions below so closing this
  # scope does not remove a no-op macro needed by the rest of the amalgamation.
  set conditionalrenames {
    {defined(SQLITE_DEBUG)} {
      sqlite3BtreeSeekCount
    }
    {!defined(SQLITE_OMIT_SHARED_CACHE)} {
      sqlite3BtreeConnectionCount sqlite3BtreeEnter sqlite3BtreeEnterAll
      sqlite3BtreeEnterCursor sqlite3BtreeSharable
    }
    {!defined(SQLITE_OMIT_SHARED_CACHE) && SQLITE_THREADSAFE} {
      sqlite3BtreeHoldsAllMutexes sqlite3BtreeHoldsMutex sqlite3BtreeLeave
      sqlite3BtreeLeaveAll sqlite3BtreeLeaveCursor sqlite3SchemaMutexHeld
    }
  }
  # test1.c links sqlite3WalTrace by its public test instrumentation name.
  set skiprename {
    disable_simulated_io_errors enable_simulated_io_errors
    sqlite3WalTrace
  }
  foreach {condition names} $conditionalrenames {
    set skiprename [concat $skiprename $names]
  }
  # Open the rename scope: the external renames from btree_orig_prefix.h, the
  # three btree type tags that prolly_btree.c redefines with a different layout,
  # and the two file-local statics that collide with prolly_btree.c.
  set prefixnames [list]
  set pin [open $srcdir/btree_orig_prefix.h rb]
  while {![eof $pin]} {
    set line [string trimright [gets $pin]]
    if {[regexp {^\s*#\s*define\s+(\S+)\s+orig_} $line all nm]} {
      if {[lsearch -exact $skiprename $nm]>=0} continue
      lappend prefixnames $nm
    }
    puts $out $line
  }
  close $pin
  foreach {condition names} $conditionalrenames {
    puts $out "#if $condition"
    foreach nm $names {
      puts $out "#define $nm orig_$nm"
    }
    puts $out "#endif"
  }
  foreach nm {Btree BtShared BtCursor sqlite3SharedCacheList
              saveAllCursors saveCursorPosition} {
    puts $out "#define $nm orig_$nm"
    lappend prefixnames $nm
  }
  # disable/enable_simulated_io_errors are no-op macros in the release build
  # (so renaming them there would strip the macro), but real functions under
  # SQLITE_TEST that the stock pager.c defines — and pager_shim.c defines the
  # unprefixed versions for the prolly pager. Rename the orig copies to orig_
  # only under SQLITE_TEST so the two don't collide.
  puts $out "#ifdef SQLITE_TEST"
  puts $out "#define disable_simulated_io_errors orig_disable_simulated_io_errors"
  puts $out "#define enable_simulated_io_errors orig_enable_simulated_io_errors"
  puts $out "#endif"
  # The stock backup.c is emitted with the orig bodies below. Its one reference
  # to struct Db.pBt (findBtree) would read prolly's Db through the stock Btree
  # layout, so DOLTLITE_ORIG_BACKUP redirects it through doltliteBtreeOrigPtr(),
  # which is defined outside this rename scope and returns the stock btree that
  # a legacy database's doltlite wrapper delegates to.
  puts $out "#define DOLTLITE_ORIG_BACKUP 1"
  # pager.c calls the backup hooks, but their sqliteInt.h prototypes were
  # inlined before this rename scope opened, so the prefixed names are still
  # undeclared here. Re-emit the two inside the scope, where the macros above
  # turn them into orig_*.
  puts $out "SQLITE_PRIVATE void sqlite3BackupRestart(sqlite3_backup *);"
  puts $out "SQLITE_PRIVATE void sqlite3BackupUpdate(sqlite3_backup *, Pgno, const u8 *);"
  # Re-inline the prefixed prototypes the orig bodies need. These headers were
  # already inlined unprefixed earlier (via sqliteInt.h), so #undef their include
  # guards to force re-processing; the rename macros above turn the re-emitted
  # prototypes into orig_*. Aggregate definitions are skipped (already defined).
  set skipstructs 1
  # doltlite-added btree API (implemented unprefixed in prolly_btree.c) must not
  # be re-declared with the orig_Btree type inside this block.
  set skipfns {
    sqlite3BtreeUsesOrig
    sqlite3BtreeProllyCachedIndexKeyCompare
    sqlite3BtreeProllyIndexRowid
    sqlite3BtreeProllyClearCompareKey
  }
  foreach {h guard} {pager.h SQLITE_PAGER_H wal.h SQLITE_WAL_H btree.h SQLITE_BTREE_H} {
    puts $out "#undef $guard"
    set available_hdr($h) 1
    copy_file $srcdir/$h
    set available_hdr($h) 0
  }
  set skipfns [list]
  set skipstructs 0
  # The orig storage bodies plus the orig_* bridge (btree_orig_api.c, which also
  # relies on the prefix + stock btreeInt.h structs and exports the unprefixed
  # origBtree* wrappers that prolly_btree.c calls).
  foreach f {pager.c wal.c btmutex.c btree.c backup.c btree_orig_api.c} {
    copy_file $srcdir/$f
  }
  # btree.c defines restoreCursorPosition() as an internal function-like macro
  # that would otherwise leak past this block and mangle prolly_btree.c's
  # same-named function.
  lappend prefixnames restoreCursorPosition
  # Close the rename scope so later files bind the unprefixed names.
  foreach nm $prefixnames {
    puts $out "#undef $nm"
  }
  foreach {condition names} $conditionalrenames {
    puts $out "#if $condition"
    foreach nm $names {
      puts $out "#undef $nm"
    }
    puts $out "#endif"
  }
  puts $out "#ifdef SQLITE_TEST"
  puts $out "#undef disable_simulated_io_errors"
  puts $out "#undef enable_simulated_io_errors"
  puts $out "#endif"
  puts $out "#undef DOLTLITE_ORIG_BACKUP"
  section_comment "doltlite: END orig_* storage engine block"
}

# doltlite: emit the prolly storage engine + version-control layer, in the
# dependency order used by PROLLY_OBJS in main.mk. prolly_btree.c/pager_shim.c
# define the unprefixed sqlite3Btree*/sqlite3Pager* entry points and call the
# orig_* engine emitted above for ATTACH'd stock databases.
proc emit_doltlite_engine_block {} {
  global out srcdir seen_hdr
  section_comment "doltlite: BEGIN prolly engine + version-control layer"
  # blake3: a single-TU amalgamation cannot pass the per-file -m{sse,avx} flags
  # the SIMD sources need, so force the portable backend (the object/release
  # builds keep SIMD). NEON is left disabled (BLAKE3_USE_NEON unset).
  foreach m {BLAKE3_NO_SSE2 BLAKE3_NO_SSE41 BLAKE3_NO_AVX2 BLAKE3_NO_AVX512} {
    puts $out "#ifndef $m"
    puts $out "#define $m 1"
    puts $out "#endif"
  }
  # Also force-disable the ARM NEON backend (autodetected on by default on
  # aarch64); its blake3_neon.c is not part of the single-file build.
  puts $out "#ifndef BLAKE3_USE_NEON"
  puts $out "#define BLAKE3_USE_NEON 0"
  puts $out "#endif"
  copy_file $srcdir/doltlite_parse.h
  set auth_system_headers {
    dirent.h errno.h fcntl.h inttypes.h limits.h stdarg.h stddef.h stdint.h
    stdio.h stdlib.h string.h sys/socket.h sys/stat.h sys/time.h time.h
    unistd.h netinet/in.h arpa/inet.h netdb.h poll.h
  }
  foreach hdr $auth_system_headers {
    unset -nocomplain seen_hdr($hdr)
  }
  set auth_seen_before [array names seen_hdr]
  puts $out "#if DOLTLITE_ENABLE_REMOTES && defined(DOLTLITE_HAVE_AUTH)"
  puts $out "#if defined(__clang__)"
  puts $out "#pragma clang diagnostic push"
  puts $out "#pragma clang diagnostic ignored \"-Wdeclaration-after-statement\""
  puts $out "#elif defined(__GNUC__)"
  puts $out "#pragma GCC diagnostic push"
  puts $out "#pragma GCC diagnostic ignored \"-Wdeclaration-after-statement\""
  puts $out "#endif"
  unset -nocomplain seen_hdr(arm_neon.h)
  foreach f [lsort [glob -nocomplain $srcdir/ed25519/*.c]] {
    set renames {}
    if {[file tail $f] eq "ge.c"} {
      set renames {select doltlite_ed25519_select}
    }
    if {[file tail $f] eq "sc.c"} {
      set renames {load_3 doltlite_ed25519_sc_load_3
                   load_4 doltlite_ed25519_sc_load_4}
    }
    if {[file tail $f] eq "sha512.c"} {
      set renames {K doltlite_ed25519_sha512_K}
    }
    copy_file_isolated $f $renames
  }
  set mbedtls_emitted {
    aes.c asn1parse.c asn1write.c base64.c bignum.c bignum_core.c
    psa_crypto_slot_management.c
    psa_crypto.c psa_crypto_aead.c psa_crypto_cipher.c psa_crypto_client.c
    psa_crypto_driver_wrappers_no_static.c psa_crypto_ecp.c psa_crypto_ffdh.c
    psa_crypto_hash.c psa_crypto_mac.c psa_crypto_random.c psa_crypto_rsa.c
    psa_crypto_storage.c psa_its_file.c psa_util.c
    chacha20.c chachapoly.c cipher.c cipher_wrap.c constant_time.c
    ecp.c ecp_curves.c ecdh.c ecdsa.c ctr_drbg.c
    debug.c dhm.c entropy.c entropy_poll.c
    gcm.c hmac_drbg.c md.c net_sockets.c oid.c pem.c pk.c pk_ecc.c pk_wrap.c
    pkcs5.c pkparse.c platform.c platform_util.c poly1305.c rsa.c rsa_alt_helpers.c
    sha1.c sha256.c sha512.c ssl_ciphersuites.c ssl_client.c
    ssl_debug_helpers_generated.c ssl_msg.c ssl_tls.c ssl_tls12_client.c
    ssl_tls13_client.c ssl_tls13_generic.c ssl_tls13_keys.c
    x509.c x509_crt.c
  }
  foreach name $mbedtls_emitted {
    set f $srcdir/mbedtls_library/$name
    set tail [file tail $f]
    set renames {}
    if {$tail eq "ecdsa.c"} {
      reset_auth_headers {mbedtls/hmac_drbg.h}
    }
    if {$tail eq "debug.c"} {
      reset_auth_headers {
        entropy_poll.h mbedtls/ssl.h mbedtls/ssl_ciphersuites.h
        mbedtls/x509.h mbedtls/x509_crl.h mbedtls/x509_crt.h
      }
    }
    if {$tail eq "sha512.c"} {set renames {K doltlite_mbedtls_sha512_K}}
    if {$tail eq "ssl_ciphersuites.c"} {
      set renames {supported_init doltlite_mbedtls_ssl_supported_init}
    }
    if {$tail eq "psa_crypto_aead.c"} {
      set renames {psa_aead_setup doltlite_mbedtls_psa_aead_setup}
    }
    if {$tail eq "psa_crypto_cipher.c"} {
      set renames {psa_cipher_setup doltlite_mbedtls_psa_cipher_setup}
    }
    if {$tail eq "psa_crypto_mac.c"} {
      set renames {psa_mac_setup doltlite_mbedtls_psa_mac_setup}
    }
    if {$tail eq "psa_crypto_slot_management.c"} {
      set renames {
        psa_global_data_t doltlite_mbedtls_psa_slot_global_data_t
        global_data doltlite_mbedtls_psa_slot_global_data
      }
    }
    if {$tail eq "ssl_tls13_client.c"} {
      set renames {
        local_err_translation doltlite_mbedtls_tls13_client_err_translation
      }
    }
    if {$tail eq "ssl_tls13_generic.c"} {
      set renames {
        local_err_translation doltlite_mbedtls_tls13_generic_err_translation
      }
    }
    if {$tail eq "ssl_tls13_keys.c"} {
      set renames {
        local_err_translation doltlite_mbedtls_tls13_keys_err_translation
      }
    }
    copy_file_isolated $f $renames
  }
  copy_file_isolated $srcdir/doltlite_creds.c
  copy_file_isolated $srcdir/doltlite_tls.c
  puts $out "#if defined(__clang__)"
  puts $out "#pragma clang diagnostic pop"
  puts $out "#elif defined(__GNUC__)"
  puts $out "#pragma GCC diagnostic pop"
  puts $out "#endif"
  puts $out "#endif"
  foreach hdr [array names seen_hdr] {
    if {[lsearch -exact $auth_seen_before $hdr]<0} {
      unset seen_hdr($hdr)
    }
  }
  # The emission list below is ordered deliberately (definitions before
  # users), so it stays hand-written rather than globbed. main.mk copies
  # every doltlite/prolly/chunk source into tsrc by wildcard, though, so
  # the two can drift: the guard after the loop fails the build when a
  # copied source is never emitted, instead of letting it go missing from
  # the amalgamation and surface later as an undefined symbol.
  set doltlite_emitted {
    prolly_hash.c prolly_xxhash.c blake3.c blake3_portable.c blake3_dispatch.c
    prolly_hashset.c prolly_node.c prolly_cache.c
    chunk_store.c chunk_store_lock.c chunk_store_refs_api.c chunk_store_commit.c chunk_wal.c chunk_refs.c chunk_index.c chunk_staging.c chunk_file.c
    prolly_cursor.c prolly_mutmap.c prolly_chunker.c prolly_mutate.c prolly_check.c
    prolly_diff.c prolly_three_way_diff.c prolly_three_way_merge.c
    prolly_btree.c prolly_btree_catalog.c prolly_btree_cursor.c
    prolly_btree_cursor_seek.c
    prolly_btree_cursor_payload.c
    prolly_btree_cursor_count.c
    prolly_btree_mutation.c prolly_btree_orig.c prolly_btree_state.c
    prolly_btree_txn.c pager_shim.c sortkey.c
    doltlite_creds.c doltlite_tls.c
    doltlite.c doltlite_core.c doltlite_cmd.c doltlite_add.c doltlite_commit_cmd.c
    doltlite_reset.c doltlite_merge_cmd.c doltlite_cherry_pick.c
    doltlite_revert.c doltlite_rebase.c doltlite_config.c
    doltlite_commit.c doltlite_ref.c doltlite_log.c
    doltlite_commit_ancestors.c doltlite_status.c doltlite_merge_status.c doltlite_diff.c doltlite_diff_table.c
    doltlite_workspace.c
    doltlite_branch.c doltlite_branches.c doltlite_checkout.c doltlite_tag.c doltlite_ancestor.c doltlite_merge.c doltlite_merge_pass1.c doltlite_merge_pass2.c doltlite_merge_predetect.c doltlite_merge_rows.c doltlite_merge_schema.c
    doltlite_conflicts.c doltlite_gc.c doltlite_chunk_walk.c
    doltlite_history.c doltlite_at.c doltlite_blame.c doltlite_schema_diff.c doltlite_patch.c
    doltlite_schemas.c doltlite_diff_stat.c doltlite_record.c doltlite_ignore.c
    doltlite_docs.c
    doltlite_tests.c
    doltlite_hashof.c doltlite_constraint_violations.c doltlite_verify_constraints.c doltlite_merge_constraints.c doltlite_merge_constraints_unique.c doltlite_merge_constraints_check.c doltlite_merge_constraints_fk.c doltlite_merge_constraints_notnull.c doltlite_merge_constraints_strict.c
    doltlite_dbpage.c doltlite_remote.c doltlite_remote_sql.c
    doltlite_http_remote.c
  }
  foreach f $doltlite_emitted {
    if {$f ni {doltlite_creds.c doltlite_tls.c}} {
      copy_file $srcdir/$f
    }
  }
  set doltlite_unemitted {}
  foreach path [lsort [concat \
      [glob -nocomplain $srcdir/doltlite*.c] \
      [glob -nocomplain $srcdir/prolly_*.c] \
      [glob -nocomplain $srcdir/chunk_*.c]]] {
    set base [file tail $path]
    if {[lsearch -exact $doltlite_emitted $base]<0} {
      lappend doltlite_unemitted $base
    }
  }
  if {[llength $doltlite_unemitted]>0} {
    error "mksqlite3c: doltlite sources copied into tsrc but never\
emitted into the amalgamation: $doltlite_unemitted. Add them to the emission\
list in tool/mksqlite3c.tcl (in dependency order), or exclude them from\
DOLTLITE_EXTRA_TSRC in doltlite.mk if they are compiled separately."
  }
  section_comment "doltlite: END prolly engine + version-control layer"
}

# Process the source files.  Process files containing commonly
# used subroutines first in order to help the compiler find
# inlining opportunities.
#
set flist {
   sqliteInt.h
   os_common.h
   ctime.c

   global.c
   status.c
   date.c
   os.c

   fault.c
   mem0.c
   mem1.c
   mem2.c
   mem3.c
   mem5.c
   mutex.c
   mutex_noop.c
   mutex_unix.c
   mutex_w32.c
   malloc.c
   printf.c
   treeview.c
   random.c
   threads.c
   utf.c
   util.c
   hash.c
   opcodes.c

   os_kv.c
   os_unix.c
   os_win.c
   memdb.c

   bitvec.c
   pcache.c
   pcache1.c
   rowset.c
   pager.c
   wal.c

   btmutex.c
   btree.c
   backup.c

   vdbemem.c
   vdbeaux.c
   vdbeapi.c
   vdbetrace.c
   vdbe.c
   vdbeblob.c
   vdbesort.c
   vdbevtab.c
   memjournal.c

   walker.c
   resolve.c
   expr.c
   alter.c
   analyze.c
   attach.c
   auth.c
   build.c
   callback.c
   delete.c
   func.c
   fkey.c
   insert.c
   legacy.c
   loadext.c
   pragma.c
   prepare.c
   select.c
   table.c
   trigger.c
   update.c
   upsert.c
   vacuum.c
   vtab.c
   wherecode.c
   whereexpr.c
   where.c
   window.c

   parse.c

   tokenize.c
   complete.c

   main.c
   notify.c

   fts3.c
   fts3_aux.c
   fts3_expr.c
   fts3_hash.c
   fts3_porter.c
   fts3_tokenizer.c
   fts3_tokenizer1.c
   fts3_tokenize_vtab.c
   fts3_write.c
   fts3_snippet.c
   fts3_unicode.c
   fts3_unicode2.c

   json.c
   rtree.c
   icu.c
   fts3_icu.c
   sqlite3rbu.c
   dbstat.c
   dbpage.c
   carray.c
   sqlite3session.c
   fts5.c
   stmt.c
}
if {$enable_recover} {
  lappend flist sqlite3recover.c dbdata.c
}
if {$doltlite} {
  # vec1 ships built into doltlite; stock amalgamations stay unchanged.
  lappend flist vec1.c
}
foreach file $flist {
  if {$doltlite && [lsearch -exact {pager.c wal.c btmutex.c btree.c backup.c} $file]>=0} {
    # The stock storage engine is replaced by the prolly engine. Emit the
    # orig_*-renamed copy once, at the slot of the first storage file.
    if {$file eq "pager.c"} { emit_doltlite_storage_block }
    continue
  }
  copy_file $srcdir/$file
  if {$doltlite && $file eq "sqliteInt.h"} {
    # Force-inline chunk_store.h (and its nested prolly_hash.h / chunk_*.h)
    # unconditionally and early. Core code (vdbe.c) includes it under
    # `#if defined(DOLTLITE_PROLLY) && !defined(SQLITE_TEST)`; if that were the
    # first occurrence, copy_file would consume the header inside a block that
    # SQLITE_TEST builds compile out, leaving PROLLY_HASH_SIZE et al. undefined
    # for the rest of the (unconditional) prolly engine. Emitting it here makes
    # those definitions visible in every configuration.
    section_comment "doltlite: chunk store / prolly headers (unconditional)"
    # The prolly/chunk/doltlite sources use INT_MAX, fixed-width ints, etc. and
    # rely on their own #include <limits.h>/<stdint.h>. copy_file dedups system
    # headers too, and the stock tree's first (conditional) <limits.h> can be
    # compiled out, leaving INT_MAX undefined. Emit them unconditionally here.
    puts $out "#include <limits.h>"
    puts $out "#include <stdint.h>"
    copy_file $srcdir/chunk_store.h
    section_comment "doltlite: network portability header"
    puts $out "#if DOLTLITE_ENABLE_REMOTES"
    set available_hdr(doltlite_net.h) 0
    copy_file $srcdir/doltlite_net.h
    puts $out "#endif"
    foreach hdr {
      errno.h string.h time.h windows.h sys/socket.h netinet/in.h arpa/inet.h
      netdb.h fcntl.h poll.h sys/time.h unistd.h
    } {
      unset -nocomplain seen_hdr($hdr)
    }
  }
}
if {$doltlite} {
  emit_doltlite_engine_block
}
foreach file $extrasrc {
  copy_file_verbatim $file
}

puts $out \
"/* Return the source-id for this library */
SQLITE_API const char *sqlite3_sourceid(void){ return SQLITE_SOURCE_ID; }"

puts $out \
"#endif /* SQLITE_AMALGAMATION */
/************************** End of sqlite3.c ******************************/"

close $out
set out {}
file rename -force $tmpfname $fname
} on error {msg opts} {
  if {$out ne ""} { catch {close $out} }
  catch {file delete -force $tmpfname}
  return -options $opts $msg
}
