#ifndef DOLTLITE_MBEDTLS_CONFIG_H
#define DOLTLITE_MBEDTLS_CONFIG_H

#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_AESCE_C
#undef MBEDTLS_AESNI_C
#undef MBEDTLS_ARIA_C
#undef MBEDTLS_CAMELLIA_C
#undef MBEDTLS_CCM_C
#undef MBEDTLS_CMAC_C
#undef MBEDTLS_DES_C
#undef MBEDTLS_ECJPAKE_C
#undef MBEDTLS_LMS_C
#undef MBEDTLS_MD5_C
#undef MBEDTLS_NIST_KW_C
#undef MBEDTLS_PKCS12_C
#undef MBEDTLS_PKCS7_C
#undef MBEDTLS_PADLOCK_C
#undef MBEDTLS_RIPEMD160_C
#undef MBEDTLS_SHA3_C
#undef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_THREADING_C
#undef MBEDTLS_THREADING_PTHREAD
#undef MBEDTLS_X509_CREATE_C
#undef MBEDTLS_X509_CRL_PARSE_C
#undef MBEDTLS_X509_CSR_PARSE_C
#undef MBEDTLS_X509_CSR_WRITE_C
#undef MBEDTLS_X509_CRT_WRITE_C

#endif
